run:
  timeout: 3m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofumpt
    - revive
    - misspell
    - bodyclose
    - unconvert
    - gocritic

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - revive
    - path: test/mocks/
      linters:
        - revive
        - gocritic
  exclude-dirs:
    - api/proto
