// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domainuser "github.com/nithibodee/7-solutions-backend-test/internal/domain/user"
	mock "github.com/stretchr/testify/mock"

	user "github.com/nithibodee/7-solutions-backend-test/internal/app/user"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function with given fields: ctx, email, password
func (_m *MockService) Authenticate(ctx context.Context, email string, password string) (string, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, email, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockService_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockService_Expecter) Authenticate(ctx interface{}, email interface{}, password interface{}) *MockService_Authenticate_Call {
	return &MockService_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, email, password)}
}

func (_c *MockService_Authenticate_Call) Run(run func(ctx context.Context, email string, password string)) *MockService_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_Authenticate_Call) Return(_a0 string, _a1 error) *MockService_Authenticate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Authenticate_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *MockService_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function with given fields: ctx
func (_m *MockService) Count(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockService_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) Count(ctx interface{}) *MockService_Count_Call {
	return &MockService_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *MockService_Count_Call) Run(run func(ctx context.Context)) *MockService_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_Count_Call) Return(_a0 int64, _a1 error) *MockService_Count_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Count_Call) RunAndReturn(run func(context.Context) (int64, error)) *MockService_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, in
func (_m *MockService) Create(ctx context.Context, in user.RegisterInput) (*domainuser.User, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domainuser.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, user.RegisterInput) (*domainuser.User, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, user.RegisterInput) *domainuser.User); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domainuser.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, user.RegisterInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - in user.RegisterInput
func (_e *MockService_Expecter) Create(ctx interface{}, in interface{}) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", ctx, in)}
}

func (_c *MockService_Create_Call) Run(run func(ctx context.Context, in user.RegisterInput)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(user.RegisterInput))
	})
	return _c
}

func (_c *MockService_Create_Call) Return(_a0 *domainuser.User, _a1 error) *MockService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(context.Context, user.RegisterInput) (*domainuser.User, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockService) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockService_Expecter) Delete(ctx interface{}, id interface{}) *MockService_Delete_Call {
	return &MockService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockService_Delete_Call) Run(run func(ctx context.Context, id string)) *MockService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_Delete_Call) Return(_a0 error) *MockService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockService) Get(ctx context.Context, id string) (*domainuser.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domainuser.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domainuser.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domainuser.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domainuser.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockService_Expecter) Get(ctx interface{}, id interface{}) *MockService_Get_Call {
	return &MockService_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockService_Get_Call) Run(run func(ctx context.Context, id string)) *MockService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_Get_Call) Return(_a0 *domainuser.User, _a1 error) *MockService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Get_Call) RunAndReturn(run func(context.Context, string) (*domainuser.User, error)) *MockService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockService) List(ctx context.Context) ([]domainuser.User, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domainuser.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domainuser.User, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domainuser.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domainuser.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) List(ctx interface{}) *MockService_List_Call {
	return &MockService_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockService_List_Call) Run(run func(ctx context.Context)) *MockService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_List_Call) Return(_a0 []domainuser.User, _a1 error) *MockService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_List_Call) RunAndReturn(run func(context.Context) ([]domainuser.User, error)) *MockService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, in
func (_m *MockService) Register(ctx context.Context, in user.RegisterInput) (*domainuser.User, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *domainuser.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, user.RegisterInput) (*domainuser.User, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, user.RegisterInput) *domainuser.User); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domainuser.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, user.RegisterInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - in user.RegisterInput
func (_e *MockService_Expecter) Register(ctx interface{}, in interface{}) *MockService_Register_Call {
	return &MockService_Register_Call{Call: _e.mock.On("Register", ctx, in)}
}

func (_c *MockService_Register_Call) Run(run func(ctx context.Context, in user.RegisterInput)) *MockService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(user.RegisterInput))
	})
	return _c
}

func (_c *MockService_Register_Call) Return(_a0 *domainuser.User, _a1 error) *MockService_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Register_Call) RunAndReturn(run func(context.Context, user.RegisterInput) (*domainuser.User, error)) *MockService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, in
func (_m *MockService) Update(ctx context.Context, id string, in user.UpdateInput) (*domainuser.User, error) {
	ret := _m.Called(ctx, id, in)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domainuser.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, user.UpdateInput) (*domainuser.User, error)); ok {
		return rf(ctx, id, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, user.UpdateInput) *domainuser.User); ok {
		r0 = rf(ctx, id, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domainuser.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, user.UpdateInput) error); ok {
		r1 = rf(ctx, id, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - in user.UpdateInput
func (_e *MockService_Expecter) Update(ctx interface{}, id interface{}, in interface{}) *MockService_Update_Call {
	return &MockService_Update_Call{Call: _e.mock.On("Update", ctx, id, in)}
}

func (_c *MockService_Update_Call) Run(run func(ctx context.Context, id string, in user.UpdateInput)) *MockService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(user.UpdateInput))
	})
	return _c
}

func (_c *MockService_Update_Call) Return(_a0 *domainuser.User, _a1 error) *MockService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Update_Call) RunAndReturn(run func(context.Context, string, user.UpdateInput) (*domainuser.User, error)) *MockService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
