// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	user "github.com/nithibodee/7-solutions-backend-test/internal/domain/user"
	mock "github.com/stretchr/testify/mock"
)

// MockTokenValidator is an autogenerated mock type for the TokenValidator type
type MockTokenValidator struct {
	mock.Mock
}

type MockTokenValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenValidator) EXPECT() *MockTokenValidator_Expecter {
	return &MockTokenValidator_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function with given fields: token
func (_m *MockTokenValidator) Validate(token string) (user.Claims, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 user.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (user.Claims, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) user.Claims); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(user.Claims)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockTokenValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - token string
func (_e *MockTokenValidator_Expecter) Validate(token interface{}) *MockTokenValidator_Validate_Call {
	return &MockTokenValidator_Validate_Call{Call: _e.mock.On("Validate", token)}
}

func (_c *MockTokenValidator_Validate_Call) Run(run func(token string)) *MockTokenValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTokenValidator_Validate_Call) Return(_a0 user.Claims, _a1 error) *MockTokenValidator_Validate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenValidator_Validate_Call) RunAndReturn(run func(string) (user.Claims, error)) *MockTokenValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenValidator creates a new instance of MockTokenValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenValidator {
	mock := &MockTokenValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
