// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	user "github.com/nithibodee/7-solutions-backend-test/internal/domain/user"
	mock "github.com/stretchr/testify/mock"
)

// MockTokenIssuer is an autogenerated mock type for the TokenIssuer type
type MockTokenIssuer struct {
	mock.Mock
}

type MockTokenIssuer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenIssuer) EXPECT() *MockTokenIssuer_Expecter {
	return &MockTokenIssuer_Expecter{mock: &_m.Mock}
}

// Issue provides a mock function with given fields: u
func (_m *MockTokenIssuer) Issue(u *user.User) (string, error) {
	ret := _m.Called(u)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*user.User) (string, error)); ok {
		return rf(u)
	}
	if rf, ok := ret.Get(0).(func(*user.User) string); ok {
		r0 = rf(u)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*user.User) error); ok {
		r1 = rf(u)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenIssuer_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type MockTokenIssuer_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - u *user.User
func (_e *MockTokenIssuer_Expecter) Issue(u interface{}) *MockTokenIssuer_Issue_Call {
	return &MockTokenIssuer_Issue_Call{Call: _e.mock.On("Issue", u)}
}

func (_c *MockTokenIssuer_Issue_Call) Run(run func(u *user.User)) *MockTokenIssuer_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*user.User))
	})
	return _c
}

func (_c *MockTokenIssuer_Issue_Call) Return(_a0 string, _a1 error) *MockTokenIssuer_Issue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenIssuer_Issue_Call) RunAndReturn(run func(*user.User) (string, error)) *MockTokenIssuer_Issue_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenIssuer creates a new instance of MockTokenIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenIssuer {
	mock := &MockTokenIssuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
